# Has all replacements for payments-mysql in a developer-sandbox instance
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: sandbox-config
      fieldPath: metadata.annotations.[turo.com/sandbox-id]
    targets:
      - select:
          kind: Job
          name: micros-schema-migration-job-1.14.3
        fieldPaths:
          - spec.template.spec.containers.0.env.0.value
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: ConfigMap
          name: payments-schema-job
        fieldPaths:
          - data.NEW_RELIC_APP_NAME
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: ServiceAccount
          name: mysql
        fieldPaths:
          - metadata.annotations.[turo.com/role-name]
        options:
          delimiter: "-"
          index: 0

    # Update AWS account ID in the service account role
  - source:
      kind: ConfigMap
      name: sandbox-config
      fieldPath: metadata.annotations.[turo.com/aws-account-id]
    targets:
      - select:
          kind: ServiceAccount
          name: mysql
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          delimiter: ":"
          index: 4

  - source:
      kind: ServiceAccount
      name: mysql
      fieldPath: metadata.annotations.[turo.com/role-name]
    targets:
      - select:
          kind: ServiceAccount
          name: mysql
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          delimiter: "/"
          index: 1

components:
  - git@github.com:turo/argocd-deployment-templates/job/schema-migration/base/replacements?ref=v18.3.0
