apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: jobs-

commonAnnotations:
  app: payments-jobs
  team: payments
  turo.com/team: payments

commonLabels:
  app.kubernetes.io/component: job
  app.kubernetes.io/name: payments-jobs

resources:
  - git@github.com:turo/argocd-deployment-templates/common/base?ref=v18.3.0
  - ../resources/payments-reconciliation
