# Has all replacements for payments in a developer-sandbox instance
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: sandbox-config
      fieldPath: metadata.annotations.[turo.com/sandbox-id]
    targets:
      - select:
          kind: ServiceAccount
          name: msvc
        fieldPaths:
          - metadata.annotations.[turo.com/role-name]
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: AnalysisTemplate
        fieldPaths:
          - spec.metrics.0.provider.job.spec.template.spec.containers.0.env.2.value
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: Rollout
        fieldPaths:
          - spec.template.spec.containers.0.env.0.value
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: Rollout
        fieldPaths:
          - spec.template.spec.containers.0.env.1.value

  # Update AWS account ID in the service account role
  - source:
      kind: ConfigMap
      name: sandbox-config
      fieldPath: metadata.annotations.[turo.com/aws-account-id]
    targets:
      - select:
          kind: ServiceAccount
          name: msvc
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          delimiter: ":"
          index: 4

  # Update versions using the extracted image tag
  - source:
      kind: Rollout
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
    targets:
      # DUNLOP_TAG
      - select:
          kind: AnalysisTemplate
        fieldPaths:
          - spec.metrics.0.provider.job.spec.template.spec.containers.0.env.4.value
  - source:
      kind: ServiceAccount
      name: msvc
      fieldPath: metadata.annotations.[turo.com/role-name]
    targets:
      - select:
          kind: ServiceAccount
          name: msvc
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          delimiter: "/"
          index: 1
