apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - service-account.yaml

patches:
  - target:
      kind: Rollout
      group: argoproj.io
      version: v1alpha1
    path: rollout.service-account.patch.yaml
