apiVersion: v1
kind: ServiceAccount
metadata:
  # name will be patched at env level
  name: payments
  annotations:
    # annotation will be patched at env level
    argocd.argoproj.io/sync-wave: "-10"
    aws-account-id: SET_AWS_ACCOUNT_ID
    eks.amazonaws.com/role-arn: SET_SERVICE_ACCOUNT_ROLE_ARN
