apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: $(APP_NAME)-job
              image: image_name:image_version
              command: ["/bin/bash", "-c", "--"]
              envFrom:
                - configMapRef:
                    name: cronjob
                    optional: false
                - secretRef:
                    name: cronjob
                    optional: false
              resources:
                requests:
                  cpu: 200m
                  memory: 200Mi
                limits:
                  cpu: 500m
                  memory: 500Mi
          restartPolicy: Never
      backoffLimit: 0
