apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml

commonAnnotations:
  team: $(TEAM)
  environment: $(ENVIRONMENT)

commonLabels:
  app.kubernetes.io/component: job
  app.kubernetes.io/name: $(APP_NAME)

configurations:
  - varref.yaml

configMapGenerator:
  - name: cronjob
