apiVersion: turo.com/V1
kind: SecretTemplate
metadata:
  name: payments
spec:
  certName: test-subaccount-2
  data:
    NEW_RELIC_API_KEY:
      path: /newrelic/test-2/rest-api-key
    NEW_RELIC_LICENSE_KEY:
      path: /newrelic/test-2/ingest-license
    NEW_RELIC_INSERT_KEY:
      path: /newrelic/test-2/insights-insert-key
    MANAGEMENT_METRICS_EXPORT_NEWRELIC_APIKEY:
      path: /newrelic/test-2/rest-api-key
