apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: payments-

commonAnnotations:
  turo.com/team: payments

commonLabels:
  app.kubernetes.io/name: payments

patches:
  - path: application-config.patch.yaml

resources:
  - ../common
  - git@github.com:turo/argocd-deployment-templates/common/base?ref=v18.3.0
  - namespace.yaml
  - resource-quota.yaml

components:
  - git@github.com:turo/argocd-deployment-templates/components/horizontal-pod-autoscaler?ref=v18.3.0
  - git@github.com:turo/argocd-deployment-templates/components/pod-disruption-budget?ref=v18.3.0
