apiVersion: turo.com/V1
kind: SecretTemplate
metadata:
  name: payments-mysql
spec:
  certName: com
  data:
    NEW_RELIC_API_KEY:
      path: /newrelic/com_rest_api_key
    NEW_RELIC_LICENSE_KEY:
      path: /newrelic/com/ingest-license
    SKEEMA_SECRET_KEY:
      path: /skeema/api_key_v0
