apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: payments-mysql.4d7c8378e52ca7a76bbd594d91205192
spec:
  encryptedData:
    NEW_RELIC_API_KEY: AgAetdIo6y0/X4GzVyjOIHK3XubABrpQuXfSSwwIkyHfJ4UEPHtAVgAeDhzrTb0u1bFVJEmTSUDttAXhJio18TrPmd08Q89ltz64S0BEn/EDelHLQm2dSkS+XgMHt9HX3NF4ZNXhM9kUk3sr4ItHBl61lv4lUN3Z7oYkqGGw9p0RcfRKcMsd26yItvi5euarinVri/SmZCn+Ushh8JuwlHynu7brRxxiOj/nYFqmwBhzYEKuwMFTccwmQGSz/jTv19vq0T4Evp7lJU5o200uiKEvKPF3GINlnIoGMMXOWqN1fqhnmxOac8yJH1j22nZkOSgQCiCLutuNbKDAER6rNw2NjE+Ty14D/UsHOwwjPUbWup8sizs5LY68xs1GC+NlGma1eG500w7lilPsMESk7vbCtUcOGrXPG5VxocCT538nw7HC9Iprd15Zy7ox0siqsufeWYHrOWpVTX09stClsu1b5UTB37EkLPD0+mR0LjNkDS/MRsK7Q8VfOrtXKO6tHcUkarw45L2bIjcXMwJpAFqjiHhWeApGN9S1klA/J40uixd6UvY30p/NnAXEJmJR+8XlBFhYAGTdADvGI0AmJl+FP+hIWB0IDx3IFhZioouhgL0OZOlPyLAowNgrOXzbVH2+DBut9sJf6pJXALZga/Kq5Sy2JEWzisqvTZWWHObC6fi0ayKYZ7ipnLE6qjs+4vO7WNuF8PNpuCyPvIwn9Rebjgq2yH4gFBY7/fT+6yjAq902KteFl60oVDz8m/XzRg==
    NEW_RELIC_LICENSE_KEY: AgAZvBl09bGSabz0fO2EsY3KilVR+2jGU4wB9Fl7UEyhcl30ZHKOMc+YHiyNye23swle+DL4pkvgvzdfdoTdpH1VlbBJGUW3I9SuhlRI1CoZEfEzbZLWFPDPXX0aHPoUnNiplEzh67KodwRakJ3BA3FDMYgfebDLKvCtxdW2l15xpxYkXXVbwSsybiIxXENY6AG8quoh/BpXG1i6vaVEWBIMwqRMRdifwAuOG1KxznZXjj2Q/FJZbUP/2czaj8aGnNQNmgVxxn30IETMaraEl69Uit+ruvBqXKQMA6iAjAv6iSRvMdpf5LpW86gUCgxMxQyZZE/A+Ffw2UV53QLHwAUlxJiBcSiZ0lvrTAbtZfEp70ND2xkDLqi+5znrriLqD1On4ECzvEYMxAKk2JB9/47jDnJ0YKm5k1uNHBFi4y2mBaSGGGhNrlmDbo3S1IpwpH7u0/JDAZPORIYUIT1tIh1JF7b3gEBfQjJ23sTJgK11ArNMCoXvLm1RVl0DKefLBIIVQ73V8t1wekqaDhme6P7k04TWNfmg5R5iFfE4dnB6J1nzrTOC88BN+EM62PN3TndFAD3GEFwBWCOfPuEUZGYHjpS4S3DsKBUA3ZE0wWJAFgE1UHt86EAChNlvp+cizllKr6VcGGTKEnAemKyeeEW/67xSMkxRSSgG4zTkVR8p9cqmv4DbUaR9nIh+ASUptYUzta4/DzUxYwclRicr2V35bWBGugL/7BrAuenULONTpJp+XnYlCkU5
    SKEEMA_SECRET_KEY: AgArWeM+FvW3ZkjBtCNo/JK5y2+IBSw8po5KCV0uzPTxUG+ULyNtHfNAHHXrkU+jxwM9lQ4mVNBLV3lY+PRH3r8lCGHxSMqKe42HVjDEGBhdLxvK0zWgBOB7yES/HrwIsCN4MCXFyXYKytTG3NpbCddwDY1/CYUZVUhGNZu9so3yMr9PP9RlbK93kA1xH5Tnd1U0TPIv+c0bxw8QQzRiPz8BX5BmNk/Ph6tXTrwwZXy+H1OCSVBpImhz5D/p0f8/9Q87kTzsiRGhllpKSKxdkVzY9fwcFYfP7g+3xbZFB4lMBtkH+nfKJnxquV65+ah+0YWKlnZNxj/lUBVf6duwbHm1R43uJWuOYPBjcRdBSc1pak7/SZ5Ubo/buYRNMq9L+1AmgiqQPOmf7KNYjUilT+mFOQ+JNilAsNwb00d5xt000KQCI5OEQawIQg6Ax3Vd41sOabLVEdwVLB6mOByMRcv2GKszx/6yjID4A4beIsAmLvFhOasNRLBXlbEp7T4CsGINmMu/Fp+3q3WjstVtp2xApKZzWtINC1EnMrqGPeWf4QR+BTaxDuGcAtabK9E+nbMrhRsVI2ldedQvB4zvhogupdM/RYR719akSBhGLKWvwFDkL6xUen79ZwbRjGrWZz4na4D59pKj+ki09D0gcaYzK5p5zIdyh7nKzERdUoEvwuKYV1Q9M1UaKehj5eZT0x68Bu5/rFw5aiM7p+2xbyVm9ltdcd6B5eRJFL6g8cPJGA==
  template:
    data: null
    metadata:
      annotations:
        cert-name: xyz
        hash-NEW_RELIC_API_KEY: 3c5ca2131b527099468a9b6632b4488d
        hash-NEW_RELIC_LICENSE_KEY: 0d35cbee8a67a598538f5b5c8d4ac295
        hash-SKEEMA_SECRET_KEY: 7b12b416e854c847c6ec30551b7f70f3
        sealedsecrets.bitnami.com/cluster-wide: "true"
        secret-hash: 4d7c8378e52ca7a76bbd594d91205192
      creationTimestamp: null
      name: payments-mysql.4d7c8378e52ca7a76bbd594d91205192
    type: Opaque
