apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app: payments-mysql
  team: payments
  turo.com/team: payments

commonLabels:
  app.kubernetes.io/name: payments-schema

resources:
  - git@github.com:turo/argocd-deployment-templates/job/schema-migration/base?ref=v18.3.0

components: []

patches:
  - path: job.service-accounts.patch.yaml
    target:
      kind: Job
      name: schema-migration

images:
  - name: image_name
    newName: turo/payments-mysql-schema
