apiVersion: v1
kind: ServiceAccount
metadata:
  # name will be patched at env level
  name: msvc
  annotations:
    # annotation will be patched at env level
    argocd.argoproj.io/sync-wave: "-10"
    turo.com/role-name: "SBX_ID-payments-msvc"
    eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/ROLE_NAME"
