on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
  issue_comment:
    types: [created, edited, deleted]

# cancel old edit events being processed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
name: Checkmate
jobs:
  validate-checklists:
    runs-on: ubuntu-latest
    name: Validate Checklist
    steps:
      - uses: actions/checkout@v3
      - name: Validate Checklists
        uses: roryq/checkmate@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            deployments/**:
              - <!--Checkmate select=1-->
              - I have tested my changes in a sandbox
              - My changes do not affect sandboxes
