on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
  issue_comment:
    types: [created, edited, deleted]

# cancel old edit events being processed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
name: Checkmate
jobs:
  validate-checklists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Checklists
        uses: roryq/checkmate@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            docs/*.md:
              - <!--Checkmate select=2-->
              - Strong Consistency
              - Availability
              - Partition Tolerance
