name: checkbox-test
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [master]

jobs:
  validate:
    name: checkbox validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Checklists
        uses: roryq/checkmate@master
#      - name: Validate Checklists
#        uses: roryq/checkmate@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          paths: |
#            docs/**/*.md:
#              - I have got the grammar police to proofread my changes.
#            schema/migrations/*.sql:
#              - There are no breaking changes in these migrations
#              - I have notified X team of the new schema changes
#            database/*.go:
#              - <!--Checkmate select=2-->
#              - Strong Consistency
#              - Availability
#              - Partition Tolerance
