name: checkbox-test
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [master]

jobs:
  validate:
    name: checkbox validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Checklists
        uses: roryq/checkmate@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            v3/sql/*.sql:
              - I have benchmarked the SQL changes
#              - <!--Checkmate select=2-->
#              - Partition Tolerance

